services:
  nginx:
    container_name: nginx-reverse-proxy
    build:
      context: docker/reverse-proxy/nginx
      dockerfile: nginx.dockerfile
    image: amony/nginx
    ports:
      - "443:443"
    volumes:
      - ./docker/reverse-proxy/nginx/config:/etc/nginx/templates:ro
      - ./docker/reverse-proxy/nginx/config/shared-proxy-settings.conf:/etc/nginx/shared-proxy-settings.conf:ro
      - certbot-data:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}
    restart: unless-stopped

  init-certificate:
    container_name: nginx-init-certificate
    profiles:
      - initial-certificate
    build:
      context: docker/reverse-proxy/certbot
      dockerfile: certbot.dockerfile
    image: amony/certbot
    volumes:
      - certbot-data:/etc/letsencrypt
    environment:
      - PORKBUN_API_KEY=${PORKBUN_API_KEY}
      - PORKBUN_SECRET_KEY=${PORKBUN_SECRET_KEY}
      - DOMAIN=${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    command:
      [
        "certbot", "certonly",
        "--authenticator", "dns-porkbun",
        "--dns-porkbun-credentials", "/etc/certbot-porkbun.ini",
        "--dns-porkbun-propagation-seconds", "60",
        "--email", "${LETSENCRYPT_EMAIL}",
        "--agree-tos",
        "--no-eff-email",
        "-d", "*.${DOMAIN}",
      ]
    restart: "no"

  certbot:
    container_name: nginx-certbot
    build:
      context: docker/reverse-proxy/certbot
      dockerfile: certbot.dockerfile
    image: amony/certbot
    depends_on:
      init-certificate:
        condition: service_completed_successfully
        required: false
    volumes:
      - certbot-data:/etc/letsencrypt
    environment:
      - PORKBUN_API_KEY=${PORKBUN_API_KEY}
      - PORKBUN_SECRET_KEY=${PORKBUN_SECRET_KEY}
    command:
      [
        "/bin/sh",
        "-c",
        "trap exit TERM; while :; do echo \"[$(date)] Running certbot renew\"; certbot renew; sleep 12h & wait $${!}; done;",
      ]
    restart: unless-stopped

volumes:
  certbot-data:
